### ISSUE TITLE
Weitere Methoden für GogGame

### ISSUE THREAD

**Issue by DanielRuf** [sissbruecker/gog-java-api#1]
Um die Download Links für Installer und Extras zu erhalten zum Beispiel?

**Comment by sissbruecker** [comment]
Loading details for games is still on my To-Do list. In future there will be a _loadDetails_ method in the GogApi class that gives you a complete GogGame object.

**Comment by sissbruecker** [comment]
Closed as duplicate of  #4 Load game details
