### ISSUE TITLE
Vermisse einige Quelldateien

### ISSUE THREAD

**Issue by DanielRuf** [sissbruecker/gog-java-api#2]
Die ganzen zusätzlich angegebenen Dateien und Klassen fehlen mir grundsätzlich im Repo.

Wäe toll, wenn du diese inklusive der .java und .class Dateien hinzufügt bzw angegeben wird, welche Versionen genutzt werden.

```
...
import org.apache.http.message.BasicNameValuePair;
import org.codehaus.jackson.map.ObjectMapper;
...
```

Auch wenn sie in der POM Datei angegeben sind, ich finde es besser wenn ich im Repo immer alle verwendeten Dateien drin habe und nicht zusätzlich noch alle Abhängigkeiten einrichten bzw nachladen muss

**Comment by sissbruecker** [comment]
Sorry, you'll have to use Maven for resolving dependencies or download them yourself.
