### ISSUE TITLE
Load game details

### ISSUE THREAD

**Issue by DanielRuf** [sissbruecker/gog-java-api#4]
**Edit (ssisbruecker)**: This issue is about loading details for a GogGame after the list of games has been retrieved.

Man kann bei https://github.com/sissbruecker/gog-java-api/blob/master/src/main/java/org/lazydevs/api/gog/GogApi.java#L133 die entsprechende JSON Datei laden (funktioniert bei mir) und entsprechend das JSONObjekt details.html mit JSoup parsen =)

`String gamedetail = HttpClientUtil.getBody(client, context, "https://secure.gog.com/account/ajax?a=gamesShelfDetails&g="+games.get(i).getId()+"");`

**Comment by sissbruecker** [comment]
Loading details for games is still on my To-Do list. In future there will be a loadDetails method in the GogApi class that gives you a complete GogGame object.

**Comment by DanielRuf** [comment]
Eventuell auch interessant, seit kurzem hier auf GitHub =) https://github.com/Sude-/lgogdownloader

**Comment by sissbruecker** [comment]
@DanielRuf 

I tried to go that route at first, since the downloader at least has a real REST API. However it does not provide you with a function to list all your games. The only related function can show you your updated games, but that's it.

**Comment by DanielRuf** [comment]
Hm well, but it seems there is some sort of JSON endpoint which gives us the games and details: http://www.gog.com/catalogue/ajax?a=getGames&tab=all_genres&genre=all_genres&price=&order=bestselling&publisher=&releaseDate=&availability=&gameMode=&rating=&search=&sort=&page=2&system=&language=&mixPage=0

Also, do we mean the same?: https://github.com/Sude-/lgogdownloader/blob/master/src/api.cpp#L70
https://github.com/Sude-/lgogdownloader/blob/master/src/api.cpp#L89
https://api.gog.com/downloader2/user

Don't know what the response of this URL is, seeams we have to authenticate first (using OAuth?) to retrieve the information we need.

**Comment by sissbruecker** [comment]
@DanielRuf 

The first URL is used on their website, but with that you get the complete games catalogue. We need something that returns only owned games.

As for the GOG downloader API used by the lgogdownloader. You can see the supported API methods by calling:

https://api.gog.com/en/downloader2/status/stable/

There is a _get_user_games_ method, but it does not return anything. The lgogdownloader code states that it is not implemented on the server side:

https://github.com/Sude-/lgogdownloader/blob/master/src/api.cpp#L222

**Comment by DanielRuf** [comment]
Hm well, I got the games and game details of the user using  Jsoup and the gameid from the gog-java-api.

**Comment by sissbruecker** [comment]
The API now has a method _loadDetails_ which returns a _DetailedGogGame_ instance.

DetailedGogGame provides the following detail data:
- Downloader and browser downloads with
  - Title
  - URL
  - OS
  - Language
  - Size
- Store URL
- Forum URL
- Support URL
- Game bonuses
  - Title
  - Type (manual, guide, artwork, etc...)
  - Downloader URL
  - Browser URL

**Comment by DanielRuf** [comment]
:+1:
