### ISSUE TITLE
many changes - no more working

### ISSUE THREAD

**Issue by DanielRuf** [sissbruecker/gog-java-api#6]
seems they have changed something.

Also `SELECTOR_SHELF = "#shshelfGamesListAll` is now `SELECTOR_SHELF = "#shelfGamesList";`

https://secure.gog.com/login does not exist anymore

And it seems the field for the login are now log_email and log_password?

**Comment by sissbruecker** [comment]
Daniel,

thanks for the heads up.

https://secure.gog.com/login still exists, and although the response returns a 404 the login actually works.

I modified the parsing of the account/details pages to the changes in their HTML, all tests should now work again.

**Comment by DanielRuf** [comment]
I think the login works because jsoup uses the login form at the top. So the part with /login is no more needed (I think so).

I will give it a try.
